services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pasteserver
      MYSQL_USER: pasteserver
      MYSQL_PASSWORD: pasteserver
    ports:
      - "3306:3306"
    volumes:
      - mariadb-db-data:/var/lib/mysql
    command: [--wait_timeout=1800]

volumes:
  mariadb-db-data:
